### ISSUE TITLE
Release 0.7 checklist

### ISSUE THREAD

**Issue by mr-c** [simd-everywhere/simde#610]
Hey @nemequ , I think we should get more practice doing releases. May I do the next one?

Is there a release checklist yet?

- [x] write [release notes](https://github.com/simd-everywhere/simde/wiki/Release-Notes)
- [x] bump `version` in `meson.build` https://github.com/simd-everywhere/simde/pull/647
- [x] bump `SIMDE_VERSION_{MAJOR,MINOR,MICRO}` in [`simde/simde-common.h`](https://github.com/simd-everywhere/simde/pull/679)
- [x] make release candidate (make sure to mark it as a "pre-release" in GitHub)
       https://github.com/simd-everywhere/simde/releases/tag/v0.7.0-rc-1
       https://github.com/simd-everywhere/simde/releases/tag/v0.7.0-rc2
- [x] test on Debian against all official and unofficial architectures using all available gcc and clang versions
       https://buildd.debian.org/status/package.php?p=simde&suite=experimental
- [x] Rebuild [all packages in Debian that use SIMDe](https://wiki.debian.org/SIMDEverywhere#Packages_Status) in `experimental` to see if there are any regressions.
     - [ ] [build summary](https://buildd.debian.org/status/package.php?p=examl%2Cpython-skbio%2Cminimap2%2Cpbcopper%2Chisat2%2Cfermi-lite%2Cbwa%2Craxml%2Ckalign%2Cfasta3%2Cplink2%2Clibssw%2Cspoa%2Cwtdbg2%2Cmmseqs2%2Csimde&suite=experimental)
     - [ ] note additional architectures that now build due to the new SIMDe release and summarize this success in the release notes
     - [x] https://buildd.debian.org/status/package.php?p=examl&suite=experimental
     - [x] https://buildd.debian.org/status/package.php?p=last-align&suite=experimental
     - [x] https://buildd.debian.org/status/package.php?p=python-skbio&suite=experimental
     - [x] https://buildd.debian.org/status/package.php?p=minimap2&suite=experimental
     - [x] https://buildd.debian.org/status/package.php?p=pbcopper&suite=experimental
     - [x] https://buildd.debian.org/status/package.php?p=hisat2&suite=experimental
     - [x] https://buildd.debian.org/status/package.php?p=vg&suite=experimental
     - [x] https://buildd.debian.org/status/package.php?p=fermi-lite&suite=experimental
     - [x] https://buildd.debian.org/status/package.php?p=bowtie2&suite=experimental
     - [x] https://buildd.debian.org/status/package.php?p=bwa&suite=experimental
     - [x] https://buildd.debian.org/status/package.php?p=raxml&suite=experimental
     - [x] https://buildd.debian.org/status/package.php?p=kalign&suite=experimental
     - [x] https://buildd.debian.org/status/package.php?p=fasta3&suite=experimental
     - [x] https://buildd.debian.org/status/package.php?p=plink2&suite=experimental
     - [ ] ~~https://buildd.debian.org/status/package.php?p=obs-studio&suite=experimental~~ Need to find another way to test obs-studio
     - [x] https://buildd.debian.org/status/package.php?p=libssw&suite=experimental
     - [x] https://buildd.debian.org/status/package.php?p=spoa&suite=experimental
     - [x] https://buildd.debian.org/status/package.php?p=wtdbg2&suite=experimental
     - [x] https://buildd.debian.org/status/package.php?p=mmseqs2&suite=experimental
            2 other packages to go
- [x] fix or ignore any errors found
- [x] make another release candidate (repeating the above as necessary)
- [x] make final release
- [x] upload an amalgamated build of the headers
- [x] create a matching tag for the simde-no-tests repo
- [ ] blog post
- [ ] email the mailing list
- [x] ping vcpkg to update, [example](https://github.com/microsoft/vcpkg/issues/15364)
- [x] copy this checklist to the wiki for next time

Here are some highlights for the release notes:

features: improve AltiVec keyword collision work-around https://github.com/simd-everywhere/simde/commit/51861662b0719bc293a472cd52395b13d7b30e9e @nemequ 

neon/min: correctly handle (and test) NaNs https://github.com/simd-everywhere/simde/commit/07d3a1fab9e6e657d8820366c85b01817d5afe9e @nemequ 

common: GCC bug #96174 is fixed in 10.2  https://github.com/simd-everywhere/simde/commit/4fa91067ed0ac5bf0450daecb2ce6ce78b280204 @nemequ 

svml: add shorter fallbacks for remaining functions https://github.com/simd-everywhere/simde/commit/4400413b273525ef4daf642ee34bf97a9d2caf28 @nemequ 
svml: GCC bug #53784 also occurs on s390x https://github.com/simd-everywhere/simde/commit/5c2d66f22ea7679e8ac5e984dbffdf1515d0c804 @nemequ

sse2: more WASM implementations: `_mm_srli_epi{16,32,64}` `_mm_srl_epi{32,64}` https://github.com/simd-everywhere/simde/commit/63e63edf6a852e5955f4cf0951b6efef503205c5 `_mm_cvt{epi32,si32,si64,si128}_*`  https://github.com/simd-everywhere/simde/commit/dd21f305c5975ffbb4334188cb29a78ecc748a28 `_mm_sra{,i}_epi{16,32}` https://github.com/simd-everywhere/simde/commit/3bd7ea9c58e7219a2dc63f9b18ddb763d3930498 @masterchef2209 

Fix compilation failures when targeting 32-bit x86 with >= SSE2 https://github.com/simd-everywhere/simde/commit/25b5fbc06ec89ded06df5a7d7c5c62690b93d182 https://github.com/simd-everywhere/simde/commit/82d00658ff5bf91feca1266eee94767e8f616d28 @nemequ 

indentation fixes https://github.com/simd-everywhere/simde/commit/a2f98fb9666e3e9897b62abaef64eaca064fdcb6 @nemequ 
cmake: emit a warning about CMake support being deprecated https://github.com/simd-everywhere/simde/commit/8cb54969a391ddaa444a3dad0896765a2d484c97 use directory contents for list of NEON tests  https://github.com/simd-everywhere/simde/commit/e0e9e31c5446eacfdf8cab91a698685f8485ddb8 @nemequ 

testing with docker improvements https://github.com/simd-everywhere/simde/commit/a5c58267e8bd81d60af5c235e417e829b9cb8311  https://github.com/simd-everywhere/simde/commit/c0c8c010f38ba538cc5ffe34a85ca09a6bb7a755 https://github.com/simd-everywhere/simde/commit/cf0cf14a33e7421e222e3908da7268ebbaf094c2 @nemequ 

README: add note about not including native headers  https://github.com/simd-everywhere/simde/commit/8011ef0d375771b35d202d746463a1997b4ab384 @nemequ

**Comment by nemequ** [comment]
> Hey @nemequ , I think we should get more practice doing releases.

This is probably a good idea.  I'm obviously not very good about making releases in general, but making some revision/patch level releases seems like a good idea.

> May I do the next one?

Sure, I don't have any problem with that.

> Is there a release checklist yet?

Not really, but it's pretty straightforward.  Just create a tag, and upload an amalgamated build of the headers. I noticed that you created a tag for the simde-no-tests repo, which I forgot about, that's probably a good idea too.  I skipped the release notes (and accompanying blog post and mailing list post) last time, which probably isn't a good idea, and it looks like you've already got a good start on the release notes anyways.

> Here are some highlights for the release notes:

There is also this small commit: bc7bfdca635ca961f52f5060b897fb146e15aae6. That actually feels more like a 0.7 change, but I don't really want to create a branch and backport all the fixes.  Maybe we should just do 0.7 next, then try to get a 0.7.1 out later with additional changes?

I'm currently trying to get older compilers working with AVX-512. I think I'm pretty close to getting GCC 5 working, but I'd like to go back a bit further if possible. If you can wait a couple days I should have that done (or possibly given up hope), it would be nice to include those fixes in the next release.

**Comment by mr-c** [comment]
> There is also this small commit: bc7bfdc. That actually feels more like a 0.7 change, but I don't really want to create a branch and backport all the fixes. Maybe we should just do 0.7 next, then try to get a 0.7.1 out later with additional changes?

We can just release the current HEAD as 0.7, yes?

**Comment by mr-c** [comment]
Ping @nemequ ; do I have permission to cut a release?

**Comment by nemequ** [comment]
Yeah, I think so.  I can't think of anything else I really want to get in before a release, and we've added quite a few optimizations (and some bug fixes), so it would be good to get a release out there to try to push people to update.

We're getting dangerously close to a complete NEON implementation, but there are still a couple big gaps (mostly fp16 and poly types) so that can wait for 0.8.

**Comment by nemequ** [comment]
I significantly overestimated NEON progress; the list in the issue was extremely incomplete.  [In reality](https://gist.github.com/nemequ/fe2f276e1e7d33659cbf77ae0d5526be) we're only 57% finished, not counting poly types and 16-bit floats. Still good progress, but completion is definitely not imminent.

**Comment by mr-c** [comment]
I tagged a pre-release so I can do test re-builds on Debian: https://github.com/simd-everywhere/simde/releases/tag/v0.7.0-rc-1

**Comment by mr-c** [comment]
Experimental test builds are in progress across all of the official and unofficial Debian architectures https://buildd.debian.org/status/package.php?p=simde&suite=experimental

**Comment by mr-c** [comment]
I made https://github.com/simd-everywhere/simde/milestone/2 to track the issues I feel that must be fixed before 0.7.0 can be released ; comments on that opinion are welcome :-)

In short: they are issues involving the architectures that Debian officially supports.

**Comment by mr-c** [comment]
With the recent commits from @nemequ all the outstanding issues I had tagged for 0.7 have been fixed, so I'm going to make another release candidate!

**Comment by mr-c** [comment]
@nemequ I've published the v0.7.0 release ; How do I build and upload the amalgamated headers?

**Comment by nemequ** [comment]
How about this?

```bash
#!/bin/sh

cd simde/
for HEADER in x86/*.h arm/neon.h; do
  if [ ! -e "../amalgamated/$(dirname "${HEADER}")" ]; then
    mkdir -p "../amalgamated/$(dirname "${HEADER}")";
  fi

  ../amalgamate.py "${HEADER}" > "../amalgamated/${HEADER}";
done
```

Then just `mv amalgamated simde-amalgamated-0.7.0 && tar jcf simde-amalgamated-0.7.0.tar.xz simde-amalgamated-0.7.0/`.

**Comment by mr-c** [comment]
@nemequ Thanks

> Then just `mv amalgamated simde-amalgamated-0.7.0 && tar jcf simde-amalgamated-0.7.0.tar.xz simde-amalgamated-0.7.0/`.

And add the simde-amalgamated tartball to this repo? I think I'm missing something here..
