### ISSUE TITLE
GSoC-2021/Glitch18: Progress tracker

### ISSUE THREAD

**Issue by Glitch18** [simd-everywhere/simde#831]
# Progress Tracker

Hello! welcome to my progress tracker. This is where I'll be keeping a track of things like what I'm currentlt working on, and the upcoming tasks from my GSoC list. 

## Tasks in progress

 - [x] Shuffle vector implementations for `st3qu8`.
 - [ ] Bug workaround for `shll_n`
 - [ ] File GCC bug report
 - [ ] OpenCV Port
---
### Implement incomplete function families. 
*Target: 26th June 2021*

Here's a [list](https://github.com/simd-everywhere/implementation-status/blob/main/neon.md) of the currently incomplete function families that I'm working on.
